collection/urls.py
from django.urls import path

from collection import views

app_name = 'collection'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:item_id>/', views.details, name='details'),
]

my_website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('collection.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

collection/models.py
from django.db import models
from django.utils import timezone
from sorl.thumbnail import ImageField


class Item(models.Model):
    post_date = models.DateTimeField('Время добавления', default=timezone.now())
    name = models.CharField('Название', max_length=50)
    key_words = models.CharField('Ключевые слова', max_length=50, default='---')
    info = models.CharField('Комментарии', max_length=1000, default='---')
    photo = ImageField('Фото', upload_to='photos', default='no_image.png')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Предмет'
        verbose_name_plural = 'Предметы'

collection/views.py
from functools import reduce
import re

from django.shortcuts import render, get_object_or_404
from django.db.models import Q

from collection.models import Item


class IndexText:
    title = 'Моя коллекция'
    headline = 'Моя коллекция'
    time = 'Врема добавления'
    name = 'Название'
    keys = 'Ключевые слова'
    comments = 'Комментарии'
    photo = 'Фото'
    search = 'ПОИСК: '
    go = 'ИСКАТЬ'
    no_item = 'Коллекция пуста'


class DetailsText:
    time = 'Врема добавления:'
    keys = 'Ключевые слова:'
    comments = 'Комментарии:'


def split_search(search_str):
    if search_str != '':
        search_list = re.split(r'\s|,|;', search_str)
        search_list = list(filter(''.__ne__, search_list))
    else:
        search_list = ['']
    return search_list


def index(request):
    search_text = ''
    if request.POST:
        search_text = request.POST['search']
        search_list = split_search(search_text)
    else:
        search_list = ['']
    query_list_1 = [Q(name__icontains=word) for word in search_list]
    query_list_2 = [Q(key_words__icontains=word) for word in search_list]
    query_list_3 = [Q(info__icontains=word) for word in search_list]
    query = reduce(lambda x, y: x | y, query_list_1 + query_list_2 + query_list_3)
    col = Item.objects.filter(query).order_by('-post_date')
    context = {'col': col, 'search_text': search_text, 'mytext': IndexText}
    return render(request, 'collection/index.html', context)


def details(request, item_id):
    item = get_object_or_404(Item, pk=item_id)
    context = {'item': item, 'mytext': DetailsText}
    return render(request, 'collection/details.html', context)

collection/templates/collection/details.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'collection/style_details.css' %}">

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ item.name }}</title>
</head>
<body>

    <img class="left_decor" src="{% static 'collection/images/bauble_left.png' %}">
    <img class="right_decor" src="{% static 'collection/images/bauble_right.png' %}">

    <h2 class="name">
        {{ item.name }}
        <a class="edit" href="/admin/collection/item/{{ item.id }}/change/">
            <img class="edit" src="{% static 'collection/images/pencil.png' %}">
        </a>
    </h2>

    <table>
        <tr>
            <td class="first"><b>{{ mytext.time }}</b></td>
            <td class="second">{{ item.post_date }}</td>
        </tr>
        <tr>
            <td class="first"><b>{{ mytext.keys }}</b></td>
            <td class="second">{{ item.key_words }}</td>
        </tr>
        <tr>
            <td colspan="2">
                <img src="{{ MEDIA_URL }}{{ item.photo.url }}" alt="{{ item.name }}" class="photo">
            </td>
        </tr>
        <tr>
            <td class="first"><b>{{ mytext.comments }}</b></td>
            <td class="second">{{ item.info }}</td>
        </tr>
    </table>

</body>
</html>

collection/templates/collection/index.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'collection/style_index.css' %}">
{% load thumbnail %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ mytext.title }}</title>
</head>
<body>

    <img class="left_decor" src="{% static 'collection/images/bauble_left.png' %}">
    <img class="right_decor" src="{% static 'collection/images/bauble_right.png' %}">

    <h1 class="headline">
        <a class="headline" href="mailto: 2elavrova@gmail.com">
            <img class="headline" src="{% static 'collection/images/email.png' %}">
        </a>
        {{ mytext.headline }}
        <a class="headline" href="/admin/collection/item/">
            <img class="headline" src="{% static 'collection/images/pencil.png' %}">
        </a>
    </h1>

    <form action="{% url 'collection:index' %}" method="post">
        {% csrf_token %}
        <label class="search" for="search">{{ mytext.search }}</label>
        <input class="text" type="text" name="search" id="search" value="{{ search_text }}">
        <input class="icon" type="image" src="{% static 'collection/images/search.png' %}">
    </form>

    {% if col %}
        <table>
            <tr>
                <th>#</th>
                <th>{{ mytext.time }}</th>
                <th>{{ mytext.name }}</th>
                <th>{{ mytext.keys }}</th>
                <th>{{ mytext.comments }}</th>
                <th>{{ mytext.photo }}</th>
            </tr>
            {% for item in col %}
                <tr>
                    <td class="center">
                        <a class="item" href="{% url 'collection:details' item.id %}">
                            {{ forloop.counter }}
                        </a>
                    </td>
                    <td class="center">
                        <a class="item" href="{% url 'collection:details' item.id %}">
                            {{ item.post_date }}
                        </a>
                    </td>
                    <td class="center">
                        <a class="item" href="{% url 'collection:details' item.id %}">
                        {{ item.name }}
                        </a>
                    </td>
                    <td class="left">
                        <a class="item" href="{% url 'collection:details' item.id %}">
                            {{ item.key_words }}
                        </a>
                    </td>
                    <td class="left">
                        <a class="item" href="{% url 'collection:details' item.id %}">
                            {{ item.info }}
                        </a>
                    </td>
                    <td class="center">
                        <a class="item" href="{% url 'collection:details' item.id %}">
                            {% thumbnail item.photo "x50" crop="center" as im %}
                                <img class="photo" src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">
                            {% endthumbnail %}
                        </a>
                    </td>
                </tr>
            {% endfor %}
        </table>
    {% else %}
        <p>{{ mytext.no_item }}</p>
    {% endif %}
</body>
</html>

<script>
    if (window.history.replaceState) {
        window.history.replaceState( null, null, window.location.href );
    }
</script>